### ISSUE TITLE
A question of License upgrade required 

### ISSUE THREAD

**Issue by CNXYQ** [ZeeshanAkbar/sublime-text-3-build-3270#2]
Hello，when I followed the steps，the sublime required to upgrade the license ，what I should do？

**Comment by ZeeshanAkbar** [comment]
Hello there,
Don't need to upgrade, otherwise if you are willing to upgrade, you'll lose
the license.

Thanks & Regards
Zeeshan Akbar

**Comment by CNXYQ** [comment]
OK，Thanks a lot !
